UtrechtUniversity/researchcloud-items

miniconda-base.yml, roles/userspace_applications/files/20-python-miniconda/miniconda
This pull request adds ansible playbook for installing pyenv and miniconda.
=> add miniconda installation script

docs/playbooks/miniconda-base.md, roles/userspace_applications/files/20-python-miniconda/miniconda
This PR adds documentation for the miniconda-base playbook
=> Add miniconda documentation

docs/index.md, docs/roles/pyenv.md
Create documentation on pyenv role
=> documentation: pyenv role

docs/playbooks/aptly.md, docs/roles/aptly_add.md, playbooks/aptly.yml
- Adds documentation for the Aptly component
- Addresses an issue with the conditional checks for the presence of gpg key parameters: on SRC, these parameters come out *defined* but empty.
=> Add docs for Aptly component and fix conditional

docs/playbooks/aptly.md, docs/roles/aptly_add.md, molecule/playbook-aptly/molecule.yml, playbooks/aptly.yml
Plus minor changes to documentation.
=> Fix aptly variable

.ansible-lint-ignore, docs/index.md, docs/playbooks/reverse_proxy.md, molecule/playbook-reverse_proxy/molecule.yml, playbooks/reverse_proxy.yml, playbooks/roles/nginx-reverse_proxy/meta/main.yml, playbooks/roles/nginx-reverse_proxy/tasks/main.yml, playbooks/roles/nginx-reverse_proxy/templates/reverseproxy.conf.j2
=> Improve reverse proxy component

docs/playbooks/ibridges.yml, docs/playbooks/irods_tools.yml, docs/roles/pip_install_systemwide.md, molecule/playbook-ibridges/molecule.yml, molecule/playbook-ibridges/verify.yml, playbooks/ibridges.yml, playbooks/irods_tools.yml, playbooks/roles/pip_install_systemwide/defaults/main.yml, playbooks/roles/pip_install_systemwide/meta/main.yml, playbooks/roles/pip_install_systemwide/tasks/main.yml, playbooks/roles/pip_install_systemwide/templates/pyenv-install.sh.j2
=> Add role pip_install_systemwide and playbook iBridges

docs/playbooks/python-workbench.md, docs/roles/pyenv.md, playbooks/python-workbench.yml, playbooks/roles/pip/tasks/main.yml, playbooks/roles/pyenv/defaults/main.yml, playbooks/roles/pyenv/molecule/pyenv-system_python/converge.yml, playbooks/roles/pyenv/molecule/pyenv-system_python/molecule.yml, playbooks/roles/pyenv/molecule/pyenv-system_python/verify.yml, playbooks/roles/pyenv/tasks/main.yml, playbooks/roles/pyenv/templates/pyenv-install.sh.j2
=> Add support for latest system python to pyenv and python-workbench

.github/workflows/check_links.yml, .github/workflows/molecule_cron.yml
Run the playbook tests in cron biweekly.
=> Add biweekly molecule run

docs/roles/anaconda.md, molecule/playbook-anaconda/molecule.yml, playbooks/roles/anaconda/defaults/main.yml, playbooks/roles/anaconda/tasks/dependencies_apt.yml, playbooks/roles/anaconda/tasks/dependencies_yum.yml, playbooks/roles/anaconda/tasks/main.yml, playbooks/roles/anaconda/templates/run_conda_init.sh.j2, playbooks/roles/default_group/tasks/main.yml, playbooks/roles/desktop_file/tasks/main.yml
Resolves #37 
This requires #191 to be merged before CI passes.
=> Anaconda: add users to anaconda group by default

playbooks/roles/rstudio/molecule/default/converge.yml, playbooks/roles/rstudio/molecule/default/molecule.yml, playbooks/roles/rstudio/tasks/debian.yml, playbooks/roles/rstudio/tasks/main.yml, playbooks/roles/rstudio/tasks/redhat.yml
=> role rstudio: minor refactor and add tests

docs/index.md, docs/playbooks/flask_app.md, docs/roles/nginx_uwsgi.md, docs/roles/uv.md, molecule/playbook-flask_app/molecule.yml, molecule/playbook-flask_app/verify.yml, molecule/playbook-reverse_proxy/molecule.yml, playbooks/flask_app.yml, playbooks/roles/nginx_uwsgi/defaults/main.yml, playbooks/roles/nginx_uwsgi/meta/main.yml, playbooks/roles/nginx_uwsgi/molecule/default/converge.yml, playbooks/roles/nginx_uwsgi/molecule/venv/prepare.yml, playbooks/roles/nginx_uwsgi/tasks/main.yml, playbooks/roles/uv/defaults/main.yml, playbooks/roles/uv/meta/main.yml, playbooks/roles/uv/molecule/default/converge.yml, playbooks/roles/uv/molecule/default/molecule.yml, playbooks/roles/uv/molecule/default/prepare.yml, playbooks/roles/uv/molecule/default/verify.yml, playbooks/roles/uv/tasks/main.yml
This PR adds a component that allows the user to serve an arbitrary Flask application using Nginx/uwsgi, with easily configurable authentication (basic, or using SSO). Performance tweaking can easily be achieved using the `flask_app_uwsgi_config` variable, which allows you to modify the `uwsgi` settings used to serve the app.
=> Add component Flask App

docs/index.md, docs/playbooks/agisoft.md, docs/roles/agisoft.md, molecule/playbook-agisoft/molecule.yml, molecule/playbook-agisoft/verify.yml, playbooks/agisoft.yml, playbooks/roles/agisoft/molecule/default/converge.yml, playbooks/roles/agisoft/molecule/default/molecule.yml, playbooks/roles/agisoft/tasks/main.yml
Add molecule tests for agisoft and lint the playbook and role.
=> Test agisoft

playbooks/roles/uu_generic/tasks/apps.yml, playbooks/roles/uu_generic/templates/run_and_pause.sh.j2
* Add more help text
* Improve styling
* Use environment variable to set SRC_TOKEN (instead of showing the token in the command passed to tmux)
* Don't deploy the script on Ubuntu 20 (older tmux versions do not support the `-e` flag for env variables)
=> Improve run and pause script

.github/workflows/molecule_playbooks.yml, .github/workflows/molecule_roles.yml
See:
* https://github.com/UtrechtUniversity/researchcloud-items/security/dependabot/2
* https://github.com/UtrechtUniversity/researchcloud-items/security/dependabot/3
=> chore: update action tj-actions/changed-files to v46

playbooks/roles/uu_generic/templates/run_and_pause.sh.j2
=> role uu_generic: run_and_pause log improvements

docs/index.md, docs/roles/require_src_docker.md, docs/roles/require_src_nginx.md, playbooks/roles/require_src_docker/defaults/main.yml, playbooks/roles/require_src_docker/meta/main.yml, playbooks/roles/require_src_docker/molecule/default/converge.yml, playbooks/roles/require_src_docker/molecule/default/molecule.yml, playbooks/roles/require_src_docker/molecule/with_rootless/converge.yml, playbooks/roles/require_src_docker/molecule/with_rootless/molecule.yml, playbooks/roles/require_src_docker/molecule/with_rootless/prepare.yml, playbooks/roles/require_src_docker/tasks/main.yml
Add a role to fail a playbook if docker is not installed.
=> Add role require_src_docker

playbooks/roles/require_src_docker/defaults/main.yml, playbooks/roles/require_src_docker/molecule/with_rootless/converge.yml, playbooks/roles/require_src_docker/tasks/main.yml
=> lint: role require_src_docker

docs/roles/pipx_install_systemwide.md, playbooks/roles/asreview_server/defaults/main.yml, playbooks/roles/asreview_server/molecule/default/converge.yml, playbooks/roles/asreview_server/molecule/default/verify.yml, playbooks/roles/asreview_server/tasks/main.yml, playbooks/roles/asreview_server/vars/main.yml, playbooks/roles/flask_app/defaults/main.yml, playbooks/roles/flask_app/tasks/main.yml, playbooks/roles/flask_app/vars/main.yml, playbooks/roles/pipx_install_systemwide/defaults/main.yml, playbooks/roles/pipx_install_systemwide/molecule/uv/converge.yml, playbooks/roles/pipx_install_systemwide/molecule/uv/molecule.yml, playbooks/roles/pipx_install_systemwide/molecule/uv/verify.yml, playbooks/roles/pipx_install_systemwide/tasks/main.yml
role flask_app: set venv location as fact available to other roles
=> role asreview_server: add asreview to default bash path

.gitignore, docs/index.md, docs/playbooks/nextflow.md, docs/roles/miniconda.md, docs/roles/nextflow.md, playbooks/roles/default_group/molecule/default/verify.yml, playbooks/roles/nextflow/defaults/main.yml, playbooks/roles/nextflow/molecule/default/molecule.yml, playbooks/roles/nextflow/molecule/default/prepare.yml, playbooks/roles/nextflow/tasks/main.yml, playbooks/roles/nextflow/vars/main.yml, playbooks/roles/stata18/molecule/default/prepare.yml
Resolves #237
**If this PR significantly modifies roles or playbooks, or adds new ones**
**If this PR adds a new role or playbook**
**If this PR changes the way users interact with ResearchCloud workspaces**
=> Nextflow latest

docs/index.md, docs/playbooks/jupyterhub.md, docs/playbooks/openvscodeserver.md, docs/roles/jupyterhub.md, docs/roles/jupyterhub_app.md, docs/roles/jupyterhub_standalone_proxy.md, docs/roles/openvscodeserver.md, molecule/playbook-jupyterhub/molecule.yml, molecule/playbook-jupyterhub/verify.yml, molecule/playbook-openvscodeserver/molecule.yml, molecule/playbook-openvscodeserver/verify.yml, playbooks/jupyterhub.yml, playbooks/openvscodeserver.yml, playbooks/roles/jupyterhub/defaults/main.yml, playbooks/roles/jupyterhub/tasks/main.yml, playbooks/roles/jupyterhub/templates/jupyterhub.service.j2, playbooks/roles/jupyterhub/vars/main.yml, playbooks/roles/jupyterhub_app/defaults/main.yml, playbooks/roles/jupyterhub_app/meta/main.yml, playbooks/roles/jupyterhub_app/tasks/main.yml, playbooks/roles/jupyterhub_app/vars/main.yml, playbooks/roles/jupyterhub_standalone_proxy/defaults/main.yml, playbooks/roles/jupyterhub_standalone_proxy/tasks/main.yml, playbooks/roles/jupyterhub_standalone_proxy/templates/sudospawner-singleuser.j2, playbooks/roles/jupyterhub_standalone_proxy/templates/utils.py.j2, playbooks/roles/jupyterhub_standalone_proxy/vars/main.yml, playbooks/roles/openvscodeserver/defaults/main.yml, playbooks/roles/openvscodeserver/meta/main.yml, playbooks/roles/openvscodeserver/tasks/main.yml, playbooks/roles/openvscodeserver/vars/main.yml
=> Add components openvscode server and jupyterhub

playbooks/ibridges.yml
Resolves #<issuenumber> **If this PR addresses an existing issue**
**If this PR significantly modifies roles or playbooks, or adds new ones**
**If this PR adds a new role or playbook**
**If this PR changes the way users interact with ResearchCloud workspaces**
=> FIX Update iBridges plugin repository URL
