- roles/fact_regular_users/tasks/main.yml
By excluding id 1000 which is by default given to the `ubuntu` user, it is skipped and will no longer fail playbooks that install something on a per-user basis that use this role.
> bug in fact_regular_users: ubuntu user is set

- docs/index.md
- docs/roles/desktop_file.md
- roles/desktop_file/defaults/main.yml
- roles/desktop_file/tasks/main.yml
An idea for a role so we can reuse our code written to install desktop file menu items through xdg-utils.
> new role: desktop_file

- roles/desktop_file/tasks/main.yml
During development of the anaconda role, a bug failed the RSC workspace deployment. This happens because the `/usr/share/desktop-directories/` folder does not exist and is not created automatically by xdg-utils. This simple addition of ensuring the folder exists, solved the issue and thus it is added to the main branch, preventing it popping up in the future in other new roles.
> bug role desktop_file: directory does not exist

- .ansible-lint
- .ansible-lint-ignore
- .env.yml
- molecule/ext/molecule-src/requirements.yml
- molecule/playbook-python-workbench/molecule.yml
- molecule/playbook-python-workbench/verify.yml
- molecule/playbook-security_updates/molecule.yml
- molecule/playbook-security_updates/verify.yml
- molecule/role-default_group/molecule.yml
- molecule/role-default_group/verify.yml
- molecule/role-fact_regular_user/converge.yml
- molecule/role-fact_regular_user/molecule.yml
- molecule/role-set_gid/converge.yml
- molecule/role-set_gid/molecule.yml
- molecule/role-set_gid/verify.yml
- playbooks/python-workbench.yml
- playbooks/roles/pyenv/meta/main.yml
- playbooks/roles/pyenv/tasks/main.yml
- playbooks/roles/python/meta/main.yml
- playbooks/roles/python/tasks/main.yml
- playbooks/roles/userspace_applications/meta/main.yml
- playbooks/roles/userspace_applications/tasks/main.yml
- requirements.yml
Now that we have molecule test for at least some playbooks, we can start linting our roles and playbooks without having to be afraid of breaking something (some linter recommendations are not trivial).
This PR:
* adds the linter config files `.ansible-lint` and `.ansible-lint-ignore`
* lints all the files in the `molecule` subdir
* lints all the files related to `python-workbench.yml`
It does not yet add a github workflow for ansible lint, as this would still result in failures for all other (unlinted) files.
> Lint python

- molecule/ext/molecule-src/.ansible-lint
- molecule/ext/molecule-src/.github/workflows/ansible-lint.yml
- molecule/ext/molecule-src/converge.yml
- molecule/ext/molecule-src/default.env.yml
- molecule/ext/molecule-src/prepare.yml
- molecule/ext/molecule-src/requirements.yml
Normally this can be done with:
`git subtree pull --prefix molecule/ext/molecule-src molecule-src main`
However, I needed to do this manually, as I had squashed the last subtree commit together with some other commits. This meant that `git subtree pull` didn't work, because it couldn't find the last time the subtree was added in the git log. So I did it 'manually', for once -- here's the command for posterity:
`git merge -s subtree -Xsubtree="molecule/ext/molecule-src" -Xtheirs molecule-src/main  --allow-unrelated-histories --squash`
> Update molecule-src subtree

- .env.yml
- .github/workflows/molecule.yml
- molecule/playbook-python-workbench/molecule.yml
- molecule/playbook-python-workbench/verify.yml
- playbooks/python-workbench.yml
- playbooks/roles/pyenv/tasks/main.yml
Use `python3-openssl` instead of `python-openssl`. Also adds a `verify.yml` for the python-workbench component, and applies `ansible-lint`.
> Fix pyenv role on Ubuntu 22. Resolves #51

- molecule/playbook-miniconda/molecule.yml
- molecule/role-miniconda/converge.yml
- molecule/role-miniconda/verify.yml
- playbooks/roles/miniconda/tasks/main.yml
- playbooks/roles/miniconda/templates/runonce_conda.sh.j2
Because of #56 boolean parameters in the portal weren't being processed as booleans.
> Fix miniconda booleans

- .github/workflows/check_links.yml
- .markdown_link_check.json
- README.md
- docs/primer/introduction.md
- docs/roles/poetry.md
- docs/roles/robotuser.md
- docs/roles/sshfs-configrobot.md
- docs/roles/tweet_collector.md
Resolves #59
This PR adds automatic link checking for links in the markdown files in this repo, which is especially relevant for the docs.
> Add markdown link checker for docs

- playbooks/roles/runonce/tasks/main.yml
I noticed we were unable to login to Desktop variants of the Python Workbench components. This turns out to be because `xrdp` starts the scripts in `/etc/profile` using `/bin/sh` instead of `bash`, and our `runonce` scripts use bash-specific syntax.
The underlying issue has been fixed in newer versions of xrdp, but Ubuntu 20.04 still has an older version. Therefore this PR patches the script used by `xrdp` to use `bash` instead of `sh`.
See https://github.com/neutrinolabs/xrdp/issues/1009
> Patch shebang in xrdp shell script

- playbooks/roles/runonce/files/uu-runonce.desktop
- playbooks/roles/runonce/meta/main.yml
- playbooks/roles/runonce/tasks/main.yml
Resolves #141.
Starts the runonce bootstrap script using a desktop startup item in `/etc/xdg/autostart`.
> Fix runonce on desktop workspaces

- playbooks/ephor.yml
- playbooks/roles/rstudio/tasks/main.yml
@dometto, i made some updates for the Ephor project. Because I added the "iRods tools " and "r workbench" components, I could remove some redundant roles from this playbook. Note that the Rstudio role is also updated. I removed the installation of R because it is done in r workbench, and centOS installation because centOS is not supported anymore if I am correct. 
Any idea if the R studio role is used elsewhere? Is it an idea to add Rstudio to r workbench by default (for desktop workspaces)? @chStaiger do you think it is useful for Emilia's project as well?
I created a workspace and everything seems to work as expected!
> update Ephor playbook and Rstudio roles 

- .github/workflows/molecule_playbooks.yml
- .github/workflows/molecule_roles.yml
- CONTRIBUTING.md
Implements the recommendations [here](https://blog.esciencecenter.nl/reduce-reuse-recycle-save-the-planet-one-github-action-at-a-time-4ab602255c3f) to run tests only on PRs marked 'ready for review'. Saves a lot of energy. :)
> chore: only run tests for non-draft PRs

- playbooks/ephor.yml
- playbooks/r-workbench.yml
> r-workbench: add rstudio on desktop workspaces.

- docs/playbooks/shared_directories.md
- molecule/playbook-shared_directories/molecule.yml
- molecule/playbook-shared_directories/verify.yml
- playbooks/shared_directories.yml
Resolves #133.
Looking at the playbook, shared directories *should* be writable already. This branch is to investigate the component.
We could possibly also make the directories optionally read-only for the group.
> Ensure shared directories are group-writable

- playbooks/roles/fact_regular_users/tasks/main.yml
Pilot version of SRC-External now uses ansible in a bench, but our fact_regular_users role installs the jmespath dependency globally, and not in the venv.
> fact_regular_users: install jmespath dependency in venv

- playbooks/agisoft.yml
- playbooks/roles/agisoft/tasks/main.yml
@dometto, the new license file of this software consists of multiple lines of text (rather than one), would this be a good way (following best practices) to get them properly from one multi-line research cloud parameter (content) to multiple lines in the text file? In the current version they are printed on one line with `\n`
I didn't test it yet, but am first interested whether there might be preferred ways to achieve this
> update agisoft version

- playbooks/roles/ibridges/defaults/main.yml
- playbooks/roles/ibridges/tasks/templates.yml
The ibridges template plugin is now a pip package and no longer needs to be installed via a git URL. This PR updates a variable name to reflect this.
> chore: update ibridges variable name

- molecule/playbook-whisper/molecule.yml
- molecule/playbook-whisper/verify.yml
@jelletreep these are very basic tests that just test whether the notebook ends up in users' homedir. I think we can't and shouldn't really test the notebook's functionality as it requires GPU's anyway?
I noticed Whisper isn't currently listed under https://utrechtuniversity.github.io/researchcloud-items/ -- could you write a quick, basic documentation about what the playbook does (e.g. that it's intended to be run in combination with the Jupyter Notebooks component)?
> playbook whisper: add basic tests

- playbooks/aptly.yml
Explicitly pass in `gpg_user` variable.
> playbook aptly: fix undefined variable error

- playbooks/roles/stata18/tasks/main.yml
- playbooks/roles/stata18/templates/stata-mp.desktop.j2
- playbooks/roles/stata18/templates/stata-se.desktop.j2
- playbooks/roles/stata18/templates/stata.desktop.j2
Stata-MP and Stata-SE were not being added to the 'Development' menu.
> role stata: fix installation of desktop files

- playbooks/aptly.yml
Resolves #225
The external aptly role uses `ansible_user` as a default GPG user, but that variable does not exist in newer versions of Ansible. Fix by setting the user explicitly.
> playbook aptly: fix user variable

- playbooks/roles/uu_generic/defaults/main.yml
- playbooks/roles/uu_generic/tasks/apps.yml
- playbooks/roles/uu_generic/templates/run_and_pause.sh.j2
This PR adds a script `/usr/local/bin/run_and_pause` to the `uu_generic` role. This role is included by the `uu-provisioning` component, so the script will be available on all UU Catalog Items.
The purpose of `run_and_pause` is to enable users to run a command and pause the workspace when that command exits. It utilizes the [ResearchCloud API](https://gw.live.surfresearchcloud.nl/v1/workspace/swagger/docs/#/workspaces/workspaces_list) to pause the workspace. The command the user wants to run is run in `tmux`, so the user can also log out of the workspace, and the command will continue running.
The user must manually enter their ResearchCloud API token when running the script. See https://servicedesk.surf.nl/wiki/display/WIKI/SRC+API on how to obtain such a token.
For testing the script, …
> feature: provision workspaces with run_and_pause script

- playbooks/asreview_server.yml
This allows all regular users on the workspace access to ASReview's data directory.
> playbook asreview_server: create default shared group

- playbooks/roles/uu_generic/tasks/apps.yml
* Ensure snaps are refreshed before attempting to install
* Also remove unneeded OS version restriction for run_and_pause
> role uu_generic: refresh snaps before install

- playbooks/roles/asreview_server/defaults/main.yml
- playbooks/roles/asreview_server/files/requirements.txt
- playbooks/roles/asreview_server/molecule/default/verify.yml
- playbooks/roles/asreview_server/tasks/cron.yml
- playbooks/roles/asreview_server/tasks/main.yml
- playbooks/roles/asreview_server/templates/asreview_sram.toml.j2
- playbooks/roles/asreview_server/templates/cron_asreview_user.sh.j2
- playbooks/roles/asreview_server/vars/main.yml
Currently SRAM users must first login to ASReview in order for them to become visible in the app. It would be nice if users were already visible, so they can be invited to projects before they are logged in.
This depends on https://github.com/asreview/asreview/pull/2192
> role asreview: support periodically adding local users

- playbooks/jupyterhub.yml
- playbooks/roles/jupyterhub/vars/main.yml
- playbooks/roles/jupyterhub_app/tasks/main.yml
The jupyterhub role by default installed packages that are not needed on a barebones installation (e.g. when using the jupyterhub_standalone_proxy role). This PR moves the installation of those dependencies to jupyterhub_app and the jupyterhub component, where they are actually needed.
> role jupyterhub: move extensions to other roles.

- playbooks/roles/alphafold3/tasks/main.yml
Since `db_path` was being created, `fetch_databases` never ran.
> Update fetch_databases command: don't re-run when files exist in db_path
